name: update-and-release-image

# only trigger on main branch
on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: ghost-google-cloud-storage:ci-test

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      -
        run: yarn
      -
        run: yarn eslint

  test-google-cloud-storage-adapter:
    needs: [eslint]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/google-cloud-storage
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      -
        run: yarn
      -
        run: yarn test

  release-image:
    needs: [test-google-cloud-storage-adapter]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 5.17.1
            file: Dockerfile
          - version: 5.17.1-alpine
            file: Dockerfile-alpine
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.file }}
          target: test
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test integration for storage adapter.
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.file }}
          target: production
          push: true
          tags: |
            mutix/ghost-google-cloud-storage:${{ matrix.version }}
